[config]
default_to_workspace = false

[tasks.add-stub-dependency-callee-caller]
args = ["stubgen", "add-stub-dependency", "--stub-wit-root", "callee-stub/wit", "--dest-wit-root", "caller/wit", "--overwrite", "--update-cargo-toml"]
command = "/Users/afsalthaj/github/golem/target/debug/golem-cli"
cwd = "."
dependencies = ["generate-callee-stub"]

[tasks.add-stub-dependency-callee2-callee]
args = ["stubgen", "add-stub-dependency", "--stub-wit-root", "callee2-stub/wit", "--dest-wit-root", "callee/wit", "--overwrite", "--update-cargo-toml"]
command = "/Users/afsalthaj/github/golem/target/debug/golem-cli"
cwd = "."
dependencies = ["generate-callee2-stub"]

[tasks.build]
args = ["build"]
command = "cargo-component"
dependencies = ["clean", "regenerate-stubs"]

[tasks.build-flow]
dependencies = ["build", "post-build"]

[tasks.build-release]
args = ["build", "--release"]
command = "cargo-component"
dependencies = ["clean", "regenerate-stubs"]

[tasks.clean]
args = ["clean"]
command = "cargo-component"

[tasks.compose-callee]
args = ["stubgen", "compose", "--source-wasm", "target/wasm32-wasi/debug/callee.wasm", "--stub-wasm", "target/wasm32-wasi/debug/callee2_stub.wasm", "--dest-wasm", "target/wasm32-wasi/debug/callee_composed.wasm"]
command = "/Users/afsalthaj/github/golem/target/debug/golem-cli"
cwd = "."

[tasks.compose-caller]
args = ["stubgen", "compose", "--source-wasm", "target/wasm32-wasi/debug/caller.wasm", "--stub-wasm", "target/wasm32-wasi/debug/callee_stub.wasm", "--dest-wasm", "target/wasm32-wasi/debug/caller_composed.wasm"]
command = "/Users/afsalthaj/github/golem/target/debug/golem-cli"
cwd = "."

[tasks.compose-release-callee]
args = ["stubgen", "compose", "--source-wasm", "target/wasm32-wasi/release/callee.wasm", "--stub-wasm", "target/wasm32-wasi/release/callee2_stub.wasm", "--dest-wasm", "target/wasm32-wasi/release/callee_composed.wasm"]
command = "/Users/afsalthaj/github/golem/target/debug/golem-cli"
cwd = "."

[tasks.compose-release-caller]
args = ["stubgen", "compose", "--source-wasm", "target/wasm32-wasi/release/caller.wasm", "--stub-wasm", "target/wasm32-wasi/release/callee_stub.wasm", "--dest-wasm", "target/wasm32-wasi/release/caller_composed.wasm"]
command = "/Users/afsalthaj/github/golem/target/debug/golem-cli"
cwd = "."

[tasks.default]
alias = "build"

[tasks.generate-callee-stub]
args = ["stubgen", "generate", "-s", "callee/wit", "-d", "callee-stub", "--wasm-rpc-path-override", "/Users/afsalthaj/github/wasm-rpc/wasm-rpc"]
command = "/Users/afsalthaj/github/golem/target/debug/golem-cli"
cwd = "."

[tasks.generate-callee2-stub]
args = ["stubgen", "generate", "-s", "callee2/wit", "-d", "callee2-stub", "--wasm-rpc-path-override", "/Users/afsalthaj/github/wasm-rpc/wasm-rpc"]
command = "/Users/afsalthaj/github/golem/target/debug/golem-cli"
cwd = "."

[tasks.post-build]
dependencies = ["compose-caller"]

[tasks.post-build-release]
dependencies = ["compose-release-caller"]

[tasks.regenerate-stubs]
dependencies = ["add-stub-dependency-callee2-callee", "add-stub-dependency-callee-caller"]

[tasks.release-build-flow]
dependencies = ["build-release", "post-build-release"]

[tasks.test]
args = ["test"]
command = "cargo-component"
dependencies = ["clean"]
