[package]
name = "caller"
edition = "2021"
version = "0.0.1"

[package.metadata.component.target]
world = "caller"
path = "wit"

[dependencies.wit-bindgen]
version = "0.17.0"
features = ["realloc"]
default-features = false

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
required-features = []
