package test:caller-stub;

interface stub-caller {
  use golem:rpc/types@0.1.0.{uri};
  use test:caller/api.{new-type};
  use test:caller/api.{another-type};
  use test:caller/api.{new-type-alias};
  use test:caller/api.{another-type-alias};
  use test:caller/api.{failing};
  use test:caller/api.{not-failing};
  use test:caller/api.{no-result};

  resource api {
    constructor(location: uri);
    run: func(name: string) -> new-type;
  }

}

world wasm-rpc-stub-caller {
  export stub-caller;
}
