package test:caller-stub;

interface stub-caller {
  use golem:rpc/types@0.1.0.{uri};

  record new-type {
    value: string
  }

  resource api {
    constructor(location: uri);
    run-self: func(name: string) -> new-type;
    run-remote: func(remote: new-type) -> string;
  }

}

world wasm-rpc-stub-caller {
  export stub-caller;
}
