package test:caller;


interface api {

  record new-type {
    value: string
  }

  run-self: func(name: string) -> new-type;
  run-remote: func(remote: new-type) -> string;
}

world caller {
  import test:callee-stub/stub-callee;
  export api;
}
