package test:caller;


interface api {

  record new-type {
    value: string
  }

  record another-type {
    value: string
  }

  type new-type-alias = option<string>;

  type another-type-alias = result<new-type-alias, string>;

  run: func(name: string) -> new-type;
}

world caller {
  import test:caller-stub/stub-caller;
  export api;
}
