package test:caller;


interface api {
  run-self: func(name: string) -> string;
  run-remote: func(remote: string) -> string;
}

world caller {
  import test:callee-stub/stub-callee;
  export api;
}
